services: 
  - postgresql
before_script:
  - create database api_test
  - python manage.py db init
  - python manage.py db migrate
  - python manage.py db upgrade
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - nosetests --with-coverage
after_success:
  - coveralls

