services: 
  - postgresql
before_script:
  - createdb api_test
  - flask db migrate
  - flask db upgrade
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - nosetests --with-coverage
after_success:
  - coveralls

