services: 
  - postgresql
before_script:
  - psql -c 'create database api_test;' -U postgres
language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - nosetests --with-coverage
after_success:
  - coveralls

