"""empty message

Revision ID: 2da4d244ffaf
Revises: 542497169e3d
Create Date: 2017-10-18 17:30:22.068000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2da4d244ffaf'
down_revision = '542497169e3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'shoppinglists_shopping_item_id_fkey', 'shoppinglists', type_='foreignkey')
    op.drop_column('shoppinglists', 'shopping_item_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shoppinglists', sa.Column('shopping_item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'shoppinglists_shopping_item_id_fkey', 'shoppinglists', 'shoppingitems', ['shopping_item_id'], ['item_id'])
    # ### end Alembic commands ###
