"""empty message

Revision ID: 542497169e3d
Revises: d984323dd301
Create Date: 2017-10-18 14:46:42.051000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '542497169e3d'
down_revision = 'd984323dd301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shoppingitems',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('itemname', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('itemname')
    )
    op.create_table('shoppinglists',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('listname', sa.String(length=50), nullable=True),
    sa.Column('shopping_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shopping_item_id'], ['shoppingitems.item_id'], ),
    sa.PrimaryKeyConstraint('list_id'),
    sa.UniqueConstraint('listname')
    )
    op.add_column(u'users', sa.Column('shopping_list_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'shoppinglists', ['shopping_list_id'], ['list_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column(u'users', 'shopping_list_id')
    op.drop_table('shoppinglists')
    op.drop_table('shoppingitems')
    # ### end Alembic commands ###
