"""empty message

Revision ID: dc3524ad7819
Revises: 
Create Date: 2017-10-23 18:52:39.088000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc3524ad7819'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=True),
    sa.Column('lastname', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('shoppinglists',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('listname', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], [u'users.user_id'], ),
    sa.PrimaryKeyConstraint('list_id'),
    sa.UniqueConstraint('listname')
    )
    op.create_table('shoppingitems',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('itemname', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('item_for_list', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_for_list'], [u'shoppinglists.list_id'], ),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('itemname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shoppingitems')
    op.drop_table('shoppinglists')
    op.drop_table('users')
    # ### end Alembic commands ###
